{{- if .Values.pvc_sync_hook.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.pvc_sync_hook.name }}-job
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
    helm.sh/hook: pre-upgrade,post-upgrade
    {{- if not .Values.pvc_sync_hook.debug }}
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- end }}
    helm.sh/hook-weight: "-1"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ .Values.pvc_sync_hook.name }}-job
    spec:
      containers:
      - name: pvc-sync
        image: ubuntu:20.04
        env:
          - name: TIER
            value: {{ .Values.tenant.tier }}
          - name: TENANT
            value: {{ .Values.tenant.name }}
        command: [ "/bin/bash", "-c", "/app/scripts/pvc_sync.sh" ]
        volumeMounts:
          - name: config-volume
            mountPath: /app/scripts
          - mountPath: "/app/{{ .Values.tenant.name }}/uploads-basic"
            name: uploads-basic
          - mountPath: "/app/{{ .Values.tenant.name }}/uploads-pro"
            name: uploads-pro
          - mountPath: "/app/{{ .Values.tenant.name }}/uploads-ultra"
            name: uploads-ultra
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.pvc_sync_hook.name }}-hook-script
            defaultMode: 484
        - name: uploads-basic
          persistentVolumeClaim:
            claimName: {{ .Values.tenant.name }}-pvc-basic
        - name: uploads-pro
          persistentVolumeClaim:
            claimName: {{ .Values.tenant.name }}-pvc-pro
        - name: uploads-ultra
          persistentVolumeClaim:
            claimName: {{ .Values.tenant.name }}-pvc-ultra
      restartPolicy: Never
      {{-  with concat .Values.pvc_sync_hook.tolerations .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
  backoffLimit: 4
{{- end }}