# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
- repo: https://github.com/norwoodj/helm-docs
  rev:  "v1.14.2"
  hooks:
    - id: helm-docs-container
      entry: jnorwood/helm-docs:v1.14.2
      args:
        # Make the tool search for charts only under the `charts` directory
        - --chart-search-root=charts/mzinga
        - --sort-values-order=file
