{{ $releaseName := .Release.Name }}
{{ $tenant := .Values.tenant.name }}
{{ $storageClasses := .Values.storageClasses }}
{{- range $k, $v := .Values.persistence.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s-%s" $tenant "pvc" $k }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if and (gt (len $storageClasses.azure) 0) (eq $k "basic") }}
  storageClassName: {{ $releaseName }}-cool
  {{- else if gt (len $storageClasses.azure) 0 }}
  storageClassName: {{ $releaseName }}-hot
  {{- else if gt (len $storageClasses.aws) 0 }}
  storageClassName: {{ printf "%s-%s-%s" "efs" $releaseName "accesspoint" }}
  {{- else }}
  storageClassName: {{ printf "%s-%s" $releaseName "enterprisemultisharerwx" }}
  {{- end }}
  resources:
    requests:
      storage: {{ $v.capacity }}
---
{{- end }}
