{{- if gt (len .Values.storageClasses.azure) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
type: Opaque
data:
  azurestorageaccountkey: {{ default "" (b64enc .Values.storageClasses.azure.storageAccount.key) }}
  azurestorageaccountname: {{ default "" (b64enc .Values.storageClasses.azure.storageAccount.name) }}
{{- end }}
