apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
data:
  CONTAINER_PORT: {{ .Values.containerPort | default 3000 | quote }}
  PAYLOAD_SECRET: {{ .Values.secret | default "none" }}
  TENANT: {{ .Values.tenant.name }}
  ENV: {{ .Values.tenant.env }}
  SENDGRID_API_KEY: {{ .Values.sendgridApiKey | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.telemetry.exporter_otlp_endpoint }}
  GRAPHQL_DISABLE_PLAYGROUND_IN_PRODUCTION: {{ .Values.graphql_disable_displayground_in_production | quote }}
  PAYLOAD_PUBLIC_ZITADEL_COOKIE_NAME: {{ .Values.tenant.name }}_idp_token
