apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cron_jobs.scheduler }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cron_jobs.scheduler }}
            image: ubuntu:22.04
            command: [ "/bin/bash", "-c", "/app/scripts/scheduler.sh" ]
            envFrom:
            - secretRef:
                name: {{ .Values.cron_jobs.scheduler }}-secrets
            volumeMounts:
              - name: config-volume
                mountPath: /app/scripts
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Values.cron_jobs.scheduler }}-script
                defaultMode: 484
          restartPolicy: Never
          {{-  with concat .Values.copy_files_hook.tolerations .Values.tolerations }}
          tolerations:
          {{- toYaml . | nindent 10 }}
          {{- end }}
      backoffLimit: 2