apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cron_jobs.scheduler }}-secrets
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
type: Opaque
stringData:
  API_KEY: {{ .Values.api.api_key | quote }}
  API_BASE_URL: {{ printf "%s/%s" .Values.api.publicURL "api" | quote }}