{{- if eq .Values.backoffice.customization.PAYLOAD_PUBLIC_DISABLE_LOCAL_STRATEGY "0" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.first_user_hook.name }}-hook-script
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
data:
  create_first_user.sh: |-
{{ .Files.Get "scripts/create_first_user.sh" | indent 4 }}
{{ end }}