{{- if eq .Values.backoffice.customization.PAYLOAD_PUBLIC_DISABLE_LOCAL_STRATEGY "0" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.first_user_hook.name }}-job
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
    helm.sh/hook: post-install
    {{- if not .Values.first_user_hook.debug }}
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- end }}
    helm.sh/hook-weight: "-1"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ .Values.first_user_hook.name }}-job
    spec:
      containers:
      - name: create-first-user
        image: ubuntu:20.04
        envFrom:
        - secretRef:
            name: {{ .Values.first_user_hook.name }}-secrets
        command: [ "/bin/bash", "-c", "/app/scripts/create_first_user.sh" ]
        volumeMounts:
          - name: config-volume
            mountPath: /app/scripts
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.first_user_hook.name }}-hook-script
            defaultMode: 484
      restartPolicy: Never
      {{-  with concat .Values.first_user_hook.tolerations .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
  backoffLimit: 4
{{ end }}