{{- $releaseName := .Release.Name }}
{{- range $k, $v := .Values.storageClasses.aws }}
{{- $storageClassSuffix := lower $k }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-{{ $releaseName }}-{{ $storageClassSuffix }}
  {{- with $v.labels }}
  labels:
    {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with $v.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner:
parameters:
  basePath: {{ $v.parameters.basePath }}
  directoryPerms: {{ $v.parameters.directoryPerms }}
  fileSystemId: {{ $v.parameters.fileSystemId }}
  provisioningMode: {{ $v.parameters.provisioningMode }}
{{- with $v.additionalParameters }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $v.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
reclaimPolicy: {{ $v.reclaimPolicy }}
allowVolumeExpansion: {{ $v.allowVolumeExpansion }}
volumeBindingMode: {{ $v.volumeBindingMode }}
---
{{- end }}
