{{ $releaseName := .Release.Name }}
{{ range $k, $v := .Values.storageClasses.azure.tier }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $releaseName }}-{{ $k }}
  {{- with $v.labels }}
  labels:
    {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with $v.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: {{ $v.provisioner }}
parameters:
  shareAccessTier: {{ $v.parameters.shareAccessTier }}
  skuName: {{ $v.parameters.skuName }}
  {{- with $v.additionalParameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
reclaimPolicy: {{ $v.reclaimPolicy }}
{{- with $v.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
allowVolumeExpansion: {{ $v.allowVolumeExpansion }}
volumeBindingMode: {{ $v.volumeBindingMode }}
---
{{- end }}
