{{- if not (or .Values.storageClasses.azure .Values.storageClasses.aws .Values.storageClasses.google) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}
