apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cron_jobs.extensibility }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cron_jobs.extensibility }}
            image: ubuntu:22.04
            command: [ "/bin/bash", "-c", "/app/scripts/copy_custom_entities.sh" ]
            env:
              - name: TENANT
                value: {{ .Values.tenant.name }}
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
            volumeMounts:
              - name: config-volume
                mountPath: /app/scripts
              - mountPath: "/app/{{ .Values.tenant.name }}"
                name: tenant-mount
          serviceAccountName: {{ .Values.tenant.name }}-sa
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Values.cron_jobs.extensibility }}-script
                defaultMode: 484
            - name: tenant-mount
              persistentVolumeClaim:
                claimName: {{ .Values.tenant.name }}-pvc-{{ .Values.tenant.tier }}
          restartPolicy: Never
          {{-  with concat .Values.cron_jobs.tolerations .Values.tolerations }}
          tolerations:
          {{- toYaml . | nindent 10 }}
          {{- end }}
      backoffLimit: 2