{{- if .Values.copy_files_hook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.copy_files_hook.name }}-secrets
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
type: Opaque
stringData:
  REPO_URL: https://mzinga:{{ .Values.copy_files_hook.azuredevops_pat }}@dev.azure.com/newesis/Code%20Name%20MZinga/_git/mzinga-{{ .Values.tenant.name }}
{{- end }}