{{- if .Values.zitadel_database.backup_enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.zitadel_database.configmap_scripts }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    releaseTime: {{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" | quote }}
data:
  psql_backup.sh: |-
{{ .Files.Get "scripts/zitadel/psql_backup.sh" | indent 4 }}
  psql_restore.sh: |-
{{ .Files.Get "scripts/zitadel/psql_restore.sh" | indent 4 }}
{{- end -}}